### ISSUE TITLE
Example does not working in Windows 10

### ISSUE THREAD

**Issue by lawlietmester** [luciotato/plus-ts-test#1]
Hi. Please rewrite your build.js code as here: 
https://github.com/vercel/next.js/pull/14231/commits/6259e80a386f31363791a49392f24908466f15bf
to support Windows platform

```
Error: spawnSync npx ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at Object.spawnSync (child_process.js:607:24)
    at Object.<anonymous> (xxx\Code\build.js:69:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync npx',
  path: 'npx',
  spawnargs: [ 'tsc', '-build', '-verbose' ]
}
```

**Comment by luciotato** [comment]
can you create a PR? 
I would prefer to fixit with an `if so=="windows"` instead of adding another dependency
